spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample?useSSL=false
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 500
      max-lifetime: 60000
      maximum-pool-size: 512
