name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.9

      - name: Set DB_TEST_ENABLE Variable
        run: |
          if echo "${{ steps.changed-files.outputs.all_modified_files }}" |
          grep -q -e "src/main/kotlin/com/example/demo/infra/repository/mapper" \
          -e "src/test/kotlin/com/example/demo/infra/repository/mapper"; then
            echo "DB_TEST_ENABLE=true" >> $GITHUB_ENV
            echo "Data Access Test will be executed."
          else
            echo "DB_TEST_ENABLE=false" >> $GITHUB_ENV
            echo "Data Access Test will be not executed."
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew build -DDB_TEST_ENABLE=$DB_TEST_ENABLE